version: '3.8'

services:
  srm_chatbot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: srm_ai_chatbot
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DATABASE_PATH=/app/chatbot.db
    volumes:
      - srm_chatbot_db:/app
    restart: always

volumes:
  srm_chatbot_db:
